// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aejotntsxxqjukonxcup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlam90bnRzeHhxanVrb254Y3VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNTI1MjgsImV4cCI6MjA1ODgyODUyOH0.NyjWSYp2kdprcpt3IUZfOEw05Tv40TTYmcEQgJ0J7vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);